name: Upload docker image and update server

# trigger on all push events to main branch
on:
  push:
    branches:
      - main

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            cd ~/brand-and-push-optimizador
            git pull